fixups
[scalacfork] Compiling 720 files to /scratch/trunk5/build/quick/classes/library
[scalacfork] /scratch/trunk5/src/library/scala/Enumeration.scala:175: error: not enough arguments for method invoke: (x$1: Any, x$2: <repeated...>[Object])Object.
[scalacfork] Unspecified value parameter x$2.
[scalacfork]       val value = m.invoke(this).asInstanceOf[Value]
[scalacfork]                           ^
[scalacfork] /scratch/trunk5/src/library/scala/Enumeration.scala:178: error: not enough arguments for method getMethod: (x$1: String, x$2: <repeated...>[Class[_]])java.lang.reflect.Method.
[scalacfork] Unspecified value parameter x$2.
[scalacfork]         val id = Int.unbox(classOf[Val] getMethod "id" invoke value)
[scalacfork]                                         ^
[scalacfork] /scratch/trunk5/src/library/scala/collection/immutable/StringLike.scala:266: error: type mismatch;
[scalacfork]  found   : Seq[AnyRef]
[scalacfork]  required: Seq[<repeated...>[Object]]
[scalacfork]     java.lang.String.format(toString, args map unwrapArg: _*)
[scalacfork]                                            ^
[scalacfork] /scratch/trunk5/src/library/scala/collection/immutable/StringLike.scala:283: error: type mismatch;
[scalacfork]  found   : Seq[AnyRef]
[scalacfork]  required: Seq[<repeated...>[Object]]
[scalacfork]     java.lang.String.format(l, toString, args map unwrapArg: _*)
[scalacfork]                                               ^
[scalacfork] /scratch/trunk5/src/library/scala/runtime/MethodCache.scala:48: error: type mismatch;
[scalacfork]  found   : Array[Class[_]]
[scalacfork]  required: Array[_ <: <repeated...>[Class[_]]]
[scalacfork]     forReceiver.getMethod(forName, forParameterTypes:_*)
[scalacfork]                                    ^
[scalacfork] /scratch/trunk5/src/library/scala/sys/process/Process.scala:103: error: overloaded method constructor ProcessBuilder with alternatives:
[scalacfork]   (<repeated...>[String])ProcessBuilder <and>
[scalacfork]   (java.util.List[String])ProcessBuilder
[scalacfork]  cannot be applied to (String)
[scalacfork]     val jpb = new JProcessBuilder(command.toArray: _*)
[scalacfork]               ^
[scalacfork] /scratch/trunk5/src/library/scala/testing/Show.scala:52: error: type mismatch;
[scalacfork]  found   : Seq[AnyRef]
[scalacfork]  required: Seq[<repeated...>[Object]]
[scalacfork]           meth.invoke(this, args1: _*)
[scalacfork]                             ^
[scalacfork] 7 errors found