ONE failure. (?)
./build/pack/bin/scalac -d /tmp test/files/pos/t4910.scala
test/files/pos/t4910.scala:5: error: could not find implicit value for parameter e: A.this.foo.type
  implicitly[foo.type]
            ^
one error found
[paulp@blossom trunk ((dc07110...))]$ cat test/files/pos/t4910.scala
class A {
  implicit object foo
  // it compiles if we uncomment this
  // implicit val bar = foo
  implicitly[foo.type]
}
[paulp@blossom trunk ((dc07110...))]$

Conflicts:
	src/reflect/scala/reflect/internal/tpe/TypeComparers.scala